---
- name: MySQL community repository addition
  yum:
    name: "{{ mysql_community_noarch_rpm }}"
    state: present

- name: Install MySQL Commnuity Server
  yum:
    name: "{{ mysql_package_list }}"

- name: Start MySQL
  service:
    name: mysqld
    state: started
    enabled: yes
